// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTkOk7Lfg5Vb9mwOIPod1R-3VopqAd-D4',
    appId: '1:357806262622:web:497c0bb3973dcf2a7d67cf',
    messagingSenderId: '357806262622',
    projectId: 'food-delivery-clone-88149',
    authDomain: 'food-delivery-clone-88149.firebaseapp.com',
    storageBucket: 'food-delivery-clone-88149.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxsywwTtfEFA7pAnxXSkLKaaYn1wVafpE',
    appId: '1:357806262622:android:e934bbdf9e72211b7d67cf',
    messagingSenderId: '357806262622',
    projectId: 'food-delivery-clone-88149',
    storageBucket: 'food-delivery-clone-88149.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqAPa9PRzKLJ-SxYg1TrWnhDG7xcoxZRc',
    appId: '1:357806262622:ios:707aa4d7ece2769b7d67cf',
    messagingSenderId: '357806262622',
    projectId: 'food-delivery-clone-88149',
    storageBucket: 'food-delivery-clone-88149.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTkOk7Lfg5Vb9mwOIPod1R-3VopqAd-D4',
    appId: '1:357806262622:web:1659558df2a278477d67cf',
    messagingSenderId: '357806262622',
    projectId: 'food-delivery-clone-88149',
    authDomain: 'food-delivery-clone-88149.firebaseapp.com',
    storageBucket: 'food-delivery-clone-88149.appspot.com',
  );
}
